name: version-beta

on:
  push:
    branches:
      - beta
    paths:
      - "src/module/**"

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: "beta"
          default: "prerelease"
          preid: "beta"
          tag-prefix: "v"
          minor-wording: "minor"
          major-wording: "major"
          patch-wording: "patch"
          bump-policy: "last-commit"
